user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

task:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
